services:
  nocode_litellm:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: nocode_litellm
    container_name: nocode_litellm
    volumes:
      - ./:/app/
    ports:
      - 8001:8001
    networks:
      - app-network

  chroma:
    image: ghcr.io/chroma-core/chroma:0.4.25.dev141
    volumes:
      - chroma-data:/chroma/chroma
    ports:
      - 8000:8000
    networks:
      - app-network

volumes:
  chroma-data:
    driver: local
  backups:
    driver: local

networks:
  net:
    driver: bridge
  app-network:
    external: true